// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6cPS49fIg_JGEWfC2TpB0IhbeUh0-RGo',
    appId: '1:179142580955:web:993e924f90f489ed514afe',
    messagingSenderId: '179142580955',
    projectId: 'embedded-system-c7e25',
    authDomain: 'embedded-system-c7e25.firebaseapp.com',
    storageBucket: 'embedded-system-c7e25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7K79OfiCdVhsCpgO6-CJGq2OQCH3bBMI',
    appId: '1:179142580955:android:912b374af54614ec514afe',
    messagingSenderId: '179142580955',
    projectId: 'embedded-system-c7e25',
    storageBucket: 'embedded-system-c7e25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6adY-ppczOJode2KN6HQOQO1MdRUWFDk',
    appId: '1:179142580955:ios:3ea219ab71f459e8514afe',
    messagingSenderId: '179142580955',
    projectId: 'embedded-system-c7e25',
    storageBucket: 'embedded-system-c7e25.appspot.com',
    iosBundleId: 'com.example.embeddedSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6adY-ppczOJode2KN6HQOQO1MdRUWFDk',
    appId: '1:179142580955:ios:3ea219ab71f459e8514afe',
    messagingSenderId: '179142580955',
    projectId: 'embedded-system-c7e25',
    storageBucket: 'embedded-system-c7e25.appspot.com',
    iosBundleId: 'com.example.embeddedSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6cPS49fIg_JGEWfC2TpB0IhbeUh0-RGo',
    appId: '1:179142580955:web:4aa31cabed7a6303514afe',
    messagingSenderId: '179142580955',
    projectId: 'embedded-system-c7e25',
    authDomain: 'embedded-system-c7e25.firebaseapp.com',
    storageBucket: 'embedded-system-c7e25.appspot.com',
  );
}
